<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\QuantumDotStudio.Core\QuantumDotStudio.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.Geometry" Version="3.1.2" />
    <PackageReference Include="HelixToolkit.Wpf" Version="3.1.2" />
  </ItemGroup>

</Project>
